license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://youtube.com/Ner07"
logoFile="logo.png"
credits="Created with MCreator - Ported to NeoForge 26.1.x"
authors="Ner07CA"
description='''Adds towers into the game which have waystones if you have the waystone mod installed.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"
